Fix file exists
DRAGNLabs/301r_retnet pull request #26
Opened 2024-01-24 22:01 UTC by jeffeardley

This pull request simply adds a check to see if the dataset already exists when running download_data.sh. It gives the user the opportunity to overwrite the existing file instead of erroring out.

2024-01-26 21:42 UTC, nprisbrey commented on download_data.py
> +    # Create the directory if it does not exist
Would this comment be redundant?

2024-01-26 21:43 UTC, nprisbrey requested changes

2024-01-26 21:43 UTC, nprisbrey commented on download_data.py
> +
I'd remove the extra carriage return.

2024-01-26 23:10 UTC, nprisbrey requested changes

2024-01-26 23:10 UTC, nprisbrey commented on download_data.py
> +import shutil
This should also be cleaned out not that it's not needed.

2024-01-29 21:51 UTC, nprisbrey approved these changes

2024-01-29 22:11 UTC, KimballNJardine approved these changes
This looks good.

2024-01-29 22:11 UTC, merged