Update README with more detailed steps + minor changes
DRAGNLabs/301r_retnet pull request #55
Opened 2024-03-22 22:30 UTC by JayOrten

- Adds detailed steps on data preprocessing in the README
- Adds an additional parameter, `hf_filesystem_path`, for downloading data from the HF filesystem. Before, we were constructing this path, but that's not a good way to do it because it depends on the repo.
- Removes quotation marks from the YAML. See: https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml
- Updates some defaults in the slurm scripts
- Add a progress bar when splitting data

2024-03-22 22:40 UTC, KimballNJardine requested changes
Please make Readme.md clearer that lines below Slurm comment apply to everything, and not just slurm, and move import statement in split_data.py. Otherwise good.

2024-03-22 22:40 UTC, KimballNJardine commented on README.md
> +More details for these steps are described in the following sections.
This reads like the following commands relate to Slurm specifically.

2024-03-22 22:40 UTC, KimballNJardine commented on src/split_data.py
> +from dask.diagnostics import ProgressBar
Move this to the from section of import statements.

2024-03-22 22:47 UTC, KimballNJardine approved these changes
Looks good.
Approved.

2024-03-22 23:20 UTC, DrewGalbraith requested changes

2024-03-22 23:20 UTC, tristancorncroissant commented on README.md
> +It should be noted that datasets can come in a variety of different formats. Currently, this repo works best with Parquet files. If the data is downloaded in a different format, the code may need to
Link the Parquet files if we're going to capitalize it IMO https://parquet.apache.org/

2024-03-22 23:20 UTC, tristancorncroissant commented on README.md
> +1. [download_data.py](./src/download_data.py), run via the [download_data.sh](./scripts/download_data.sh) script, can download data through the HuggingFace Filesystem. To do this, ensure that the cor
Start with "By running [download_data.py](./src/download_data.py) via the..."

2024-03-22 23:20 UTC, DrewGalbraith commented on README.md
> +Optionally, within [split_data.py](./src/split_data.py), you can specify to shuffle the data while splitting. This is more expensive for larger datasets. Any other preprocessing and pretokenization s
Replace 

"Any other preprocessing and pretokenization steps should occur within this step." 

with

"This and any other preprocessing or pretokenization steps should occur here prior to splitting the data."

2024-03-22 23:20 UTC, DrewGalbraith commented on README.md
> +1. [download_data.py](./src/download_data.py), run via the [download_data.sh](./scripts/download_data.sh) script, can download data through the HuggingFace Filesystem. To do this, ensure that the cor
Replace 

"download data through the HuggingFace Filesystem."

with

"download data through the [HuggingFace Filesystem].(https://huggingface.co/docs/huggingface_hub/v0.22.0.rc0/en/package_reference/hf_file_system#huggingface_hub.HfFileSystem)"

2024-03-25 21:31 UTC, DrewGalbraith approved these changes

2024-03-25 21:31 UTC, merged