Complexity analysis
DRAGNLabs/301r_retnet pull request #63
Opened 2024-03-27 15:27 UTC by jeffeardley

This pull request adds the ability to measure the time it takes for a model to generate tokens. This system has the ability to measure the latency of individual token generation, and a sequence of a defined length of tokens. It modifies the template yaml file and the run_eval.sh to add this functionality. The script can also test multiple sequence lengths in a single run by editing the yaml file. If you have any suggested features or changes, please let me know.

2024-03-27 17:12 UTC, DrewGalbraith requested changes
I did an initial review.

There are a lot of good things going on here (e.g. clean logic, good hyperparameters, informative variable names, one-purpose functions, etc.)

There are some formatting things and missing default behaviors, along with some more substantial issues that would impede running the code, if I'm understanding it correctly. Have we run this all the wya through yet?

I'm happy to rereview once we address this first round of comments.

2024-03-27 17:12 UTC, tristancorncroissant commented on configs/template_config.yaml
>  tasks:
I like adding latency to the `tasks` list here, but lets make a note in the comment that latency does not run through the lm_eval harness.

2024-03-27 17:12 UTC, tristancorncroissant commented on src/eval_main.py
> +# from eval_suite import run_eval
Uncomment this import and the corrresponding usage below. They should run no matter what, and if only latency is in the task list, it will just run it, do nothing, and move on (I think...).

2024-03-27 17:12 UTC, tristancorncroissant commented on slurm/run_eval.sh
> +python3 ../../src/eval_main.py ../../configs/user_configs/<YOUR_CONFIG_HERE>.yaml
Good idea on splitting up eval objectives into seperate py files and on the rename below for clarity. +10 pts -->Eardleys

2024-03-27 17:12 UTC, tristancorncroissant commented on src/eval_latency.py
> +from generate import generate_text_length_n
Alphabetize the bad boyz before Kimball sees them!

2024-03-27 17:12 UTC, tristancorncroissant commented on src/eval_latency.py
> +    test_sequence_lengths = [i * (config.seq_len // config.seq_len_frac) for i in range(1, config.seq_len_frac)]
If I set this to `0` or `None`, this should have a default setting that avoids any errors. Something simple like:
```
if not config.seq_len_frac:
    config.seq_len_frac = 1
``` 
And you'd want to add the default value + behavior to the hyperparam comment in the yaml.

2024-03-27 17:12 UTC, tristancorncroissant commented on src/eval_latency.py
> +    test_sequence_lengths.append(config.seq_len - 1)
This is not the same as the yaml comment which says `# Example: sequence_length=100, seq_len_frac=10, test_sequence_lengths=[0,10,20,...,80,90,100]`.
Should that last number not be `99`? Or should `append(config.seq_len - 1)` be `.append(config.seq_len)`?

2024-03-27 17:12 UTC, tristancorncroissant commented on src/eval_latency.py
> +        for _ in range(config.num_latency_trials):
Again, if this is set to `0` or `None`? And add default behavior to the yaml.

2024-03-27 17:12 UTC, DrewGalbraith commented on src/eval_latency.py
> +        else:
A comment explaining what cases this if-else aims to handle would be nice. More comments throughout this whole python file would be nice, actually. The print statements, type hinting, and variable names help, but comments are extra nice.

2024-03-27 17:12 UTC, DrewGalbraith commented on src/eval_latency.py
> +    random_tokens = [random.randint(0, config.vocab_size - 1) for _ in range(n_tokens)]
`n_tokens` is not defined anywhere; did you mean `n_tokens_to_generate`?

2024-03-27 17:12 UTC, DrewGalbraith commented on src/utils.py
> +import time
Alphabetize

2024-03-27 17:12 UTC, DrewGalbraith commented on src/generate.py
> +def generate_text_length_n(config: Struct, n: int, input_tokens: torch.Tensor):
I never saw input_tokens become anything but a python list of random number representing tokens from our vocabulary; is there a reason it's been type-hinted as a `torch.Tensor`?

2024-03-27 17:23 UTC, jeffeardley commented
Thanks Drew, I agree with your comments, I'll fix all those when I get a chance later today. I think this might be one commit behind my local repo, but yes the version I've been testing does work.

2024-03-29 22:43 UTC, KimballNJardine submitted a review, later dismissed
The code runs and works, and does not break transformer or retnet.
Approved.

2024-03-29 22:43 UTC, KimballNJardine commented on src/utils.py
> +import time
Alphabetize

2024-03-30 20:47 UTC, DrewGalbraith approved these changes

2024-04-01 21:09 UTC, KimballNJardine requested changes
I have a few questions. Please respond to comments.

2024-04-01 21:09 UTC, KimballNJardine commented on test.py
Is there a reason test.py is here?

2024-04-01 21:09 UTC, KimballNJardine commented on slurm/run_eval.sh
> +python3 ../../src/eval_main.py ../../configs/user_configs/template_config.yaml
template_config.yaml vs <YOUR_CONFIG_HERE>

2024-04-01 21:09 UTC, KimballNJardine commented on src/eval_latency.py
> +    print(random_tokens)
Do we need this print statement here?

2024-04-01 21:09 UTC, KimballNJardine commented on src/generate.py
> +        model = TransformerModel(config)
Add in support for LongNet.

2024-04-01 21:09 UTC, KimballNJardine commented on src/utils.py
> +            predictions = F.softmax(predictions, dim=-1)
Why are all these items below predictions not in the timer?

2024-04-01 21:48 UTC, KimballNJardine reviewed
This generally looks good. If someone else can review eval_suite and generate as I made changes that would be good.

2024-04-01 22:07 UTC, DrewGalbraith approved these changes
Good job, everyone! Especially @JayOrten

2024-04-01 22:07 UTC, KimballNJardine approved these changes

2024-04-01 22:07 UTC, DrewGalbraith commented
April Fools! (@jeffeardley, good job)

2024-04-01 22:07 UTC, merged